#!/usr/bin/perl
use v5.14.1;

while (<>) {
    chomp;
    my ( $chapter, $url ) = split ',', $_;
    if ( $chapter !~ /^[a-z-]+$/ || $url !~ qr{^https://docs\.google\.com/document/d/([A-Za-z_0-9-]+)/edit} ) {
        warn "Kapitelname oder Google URL passt so nocht: $_\n";
        exit 1;
    }

    my $fileid = $1;
    my $name = $chapter eq "einleitung" ? "index" : $chapter;
    my $source = "../$name.md";
    if ( ! -e $source ) {
        warn "Kapiteldatei nicht gefunden: $source\n"; 
        exit 1;
    }

    say "\n# $chapter";
    if (!system("pandoc $source -o $chapter.docx -M lang=de && make $chapter.md")) {
        if (system("git diff --quiet --exit-code $chapter.md")) {
            say "Die Datei $chapter.docx muss nach Google Drive hochgeladen werden um https://docs.google.com/document/d/$fileid zu ersetzen";
            say "Anschließend kann $chapter.md gespeichert werden (`git add $chapter.md; git commit`)";
        }
    }
}
